# BOT settings

BOT_TOKEN = "" # <-- The token of the BOT
BOT_PREFIX = "?" # <-- The prefix of the BOT
OWNER = 012345678910121314 # <-- Use your own User ID
START_MESSAGE = "Bot is starting"


# SCRIPT settings

BAN_COUNT_LIMIT = 10000 # <-- The max amount of limit for looping throught the list of bans (integer)
DB_NAME = "bot_test" # <-- The name of the database (string)
DEFAULT_LANGUAGE = "english" # <-- The default language of the BOT. ("english", "magyar", "deutsch")
MAX_INDEX = 20 # <-- The maximum amount of messages can be send without updating the DB (integer)
DELAY = 5 # <-- This is the delay in seconds for updating the DB (integer)

# LOCALES

# English
english = {
    "TOTAL_BANS_MSG": "Total number of bans: ",
    "TOTAL_MEMBERS_MSG": "Total number of members: ",
    "SYNC_COMMANDS_MSG": "Successfully synced this amount of command(s): ",
    "SYNC_ERROR_MSG": "Error while trying to sync: ",
    "RELOAD_MSG": "Successfully reloaded: ",
    "RELOAD_ERROR_MSG": "Error while trying to reload: ",
    "UPDATE_LANG_MSG": "You successfully updated the language to this: ",
    "UPDATE_LANG_ERROR_MSG": "Something went wrong, try again later! Error: ",
    "CHECK_FAILURE_MSG": "You do not have access to this command.",
}

# Hungarian
magyar = {
    "TOTAL_BANS_MSG": "Összes kitiltás száma: ",
    "TOTAL_MEMBERS_MSG": "Összes tag száma: ",
    "SYNC_COMMANDS_MSG": "Sikeresen szinkronizálva lett ennyi parancs: ",
    "SYNC_ERROR_MSG": "Hiba történt szinkronizálás közben: ",
    "RELOAD_MSG": "Sikeresen újratöltve: ",
    "RELOAD_ERROR_MSG": "Hiba történt újratöltés közben: ",
    "UPDATE_LANG_MSG": "Sikeresen megváltoztattad a nyelvet erre: ",
    "UPDATE_LANG_ERROR_MSG": "Valami hiba történt, próbáld meg újra később! Hiba: ",
    "CHECK_FAILURE_MSG": "Nincsen hozzáférésed ehhez a parancshoz.",
}

# German - TODO
deutsch = {
    "TOTAL_BANS_MSG": "Total number of bans: ",
    "TOTAL_MEMBERS_MSG": "Total number of members: ",
    "SYNC_COMMANDS_MSG": "Successfully synced this amount of command(s): ",
    "SYNC_ERROR_MSG": "Error while trying to sync: ",
    "RELOAD_MSG": "Successfully reloaded: ",
    "RELOAD_ERROR_MSG": "Error while trying to reload: ",
    "UPDATE_LANG_MSG": "You successfully updated the language to this: ",
    "UPDATE_LANG_ERROR_MSG": "Something went wrong, try again later! Error: ",
    "CHECK_FAILURE_MSG": "You do not have access to this command.",
}